<a href="https://colab.research.google.com/github/Petegichana/Machine-Learning-Algorithms/blob/main/SpeechRecognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CONVERTING TEXT TO SPEECH

In [5]:
!pip install gTTS

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
from gtts import gTTS
myText = 'I Love Arsenal and we will win the premier league 2023, come on gunners'
language = 'en'


In [7]:
speech = gTTS(text=myText, lang=language, slow=False)
speech.save('speech.mp3')

In [8]:
#play audio
from IPython.display import Audio
from IPython.display import display

sound_file = 'speech.mp3'
sound = Audio(sound_file, autoplay=True)
display(sound)


SPEECH TO TEXT

In [9]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 41.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 86.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 20.5 MB/s eta 0:00:00


In [10]:
#librosa : Library used for analysing and processing audio signals
import librosa 
import torch #used to analyse the vector representaion of the sound

#pre training models
from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
#Wav2Vec2ForCTC: Pretrained CNN model for speech recognition
#Wav2Vec2Tokenizer: Used to process audion data by converting them into chunks of vectors

In [11]:
from IPython.display import Audio
from IPython.display import display

sound_file = 'speech.mp3'
sound = Audio(sound_file, autoplay=True)
display(sound)


In [12]:
audio, rate = librosa.load('speech.mp3', sr=16000)#16000 means we are recording 16000 audio samples per second
print(rate)


16000


In [13]:
#using pretrained model
tokenizer = Wav2Vec2Tokenizer.from_pretrained('facebook/wav2vec2-base-960h')#developed by Facebook AI research, 960 hours of speech data from diverse sources e.g audio book


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.9/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:752: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


In [14]:
model = Wav2Vec2ForCTC.from_pretrained('facebook/wav2vec2-base-960h')


Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [15]:
input_values = tokenizer(audio, return_tensors='pt').input_values
#pt - return audio data as python tensors, rather than python lists
print(input_values)

tensor([[0.0025, 0.0025, 0.0025,  ..., 0.0025, 0.0025, 0.0025]])


In [16]:
logits = model(input_values).logits #logits are tensors that are converted to a probability value between 0 & 1
logits

tensor([[[ 15.2722, -27.8628, -27.5649,  ...,  -5.7059,  -7.5932,  -7.9946],
         [ 15.3146, -27.5575, -27.2506,  ...,  -5.5690,  -7.6367,  -7.9358],
         [ 15.2510, -26.7367, -26.4540,  ...,  -4.3418,  -7.4839,  -7.4716],
         ...,
         [ 15.3630, -27.6328, -27.3477,  ...,  -5.4780,  -7.5468,  -7.5638],
         [ 15.4448, -27.9500, -27.6552,  ...,  -5.5643,  -8.0456,  -7.6537],
         [ 15.5060, -27.9775, -27.6744,  ...,  -5.6429,  -8.2012,  -7.6862]]],
       grad_fn=<ViewBackward0>)

In [17]:
prediction = torch.argmax(logits, dim = -1)
print(prediction)

tensor([[ 0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  4,  4,  4,  0, 15, 15,  0,  0,
          0,  0,  8,  0,  0, 25,  0,  5,  4,  4,  4,  0,  0,  0,  0,  7,  0, 13,
         13,  0,  0,  0,  0, 12,  0,  0,  0,  5,  0,  0,  9,  0,  0,  0,  7,  0,
         15,  0,  0,  0,  4,  4,  0,  7,  9,  0, 14,  4,  4, 18,  0,  0,  5,  0,
          4,  4, 18,  0,  0, 10, 15,  0,  0, 15,  0,  4,  0, 18,  0,  0, 10, 10,
          0,  9,  0,  0,  4,  4,  6, 11,  0,  5,  4,  4,  0, 23,  0, 13,  0,  0,
          7,  0,  0,  0, 17,  0,  0, 10,  0,  0,  0, 13, 13,  0,  0,  4,  4,  0,
         15, 15,  0,  5,  5,  0,  7,  0, 21, 16, 16,  5,  5,  4,  4,  4,  0,  6,
          0, 18,  0,  0,  5,  9,  9,  0,  6,  0, 22,  0,  4,  4,  4,  0,  6,  0,
         18,  0,  0,  5,  0,  9,  0,  6,  0, 22, 22,  0,  4,  4,  0,  6,  6, 11,
         11, 13, 13,  0,  0,  5,  0,  0,  0,  5,  5,  4,  4,  4,  4,  4,  4,  0,
          0,  0,  0,  0,  0,  0,  0, 19,  0,  0,  0,  8,  0, 17,  0,  5,  4,  4,
          0,  0,  0,  8,  9,

In [18]:
transcription = tokenizer.batch_decode(prediction)
print(transcription) #transcription is the process of converting vector representation of audio file

['I LOVE ARSENAL AND WE WILL WIN THE PRAMIR LEAGUE TWENTY TWENTY THREE COME ON GUNNERS']
